services:
    orchestrator:
        build: ./orchestrator/
        ports:
            - "80:4000"
        environment:
            - "PASSWORD_REDIS=gK98pHZf23CtFxHl6TZ101Ijg4VUOVVw"
            - "HOST_REDIS=redis-18138.c54.ap-northeast-1-2.ec2.cloud.redislabs.com"
            - "APP_SERVICE_URL=http://app-service:4003"
            - "USER_SERVICE_URL=http://user-service:4002"
    app-service:
        build: ./services/app
        ports:
            - "8003:4003"
        environment:
            SECRET: ${SECRET_KEY}
            NODE_ENV: production
            DATABASE_URL: ${DATABASE_URL}
    user-service:
        build: ./services/users
        ports:
            - "8002:4002"