FROM node:18.16.0

WORKDIR /orchestrator

ENV PORT=4000

COPY ["package.json","package-lock.json","/orchestrator"]

RUN npm install

RUN npm install -g nodemon

COPY ./ ./

CMD ["npm", "run", "start"]