FROM node:18.16.0

WORKDIR /services/users

ENV PORT=4002

COPY ["package.json","package-lock.json","/services/users"]

RUN npm install 

RUN npm install -g nodemon

COPY ./ ./

CMD ["npm", "run", "start"]